### ISSUE TITLE
【反馈】

### ISSUE THREAD

**Issue by S-Joan** [cyear/chaoxing#2]
出现报错<class 'AttributeError'>
错误文件名：/root/chaoxing/main.py
错误行数：235
错误原因:'NoneType' object has no attribute 'get'
 
![1](https://user-images.githubusercontent.com/86223309/191559740-30e929e5-9b97-43f5-b65a-4d5c3171402c.png)

**Comment by cyear** [comment]
> 出现报错<class 'AttributeError'> 错误文件名：/root/chaoxing/main.py 错误行数：235 错误原因:'NoneType' object has no attribute 'get'
> 
> ![1](https://user-images.githubusercontent.com/86223309/191559740-30e929e5-9b97-43f5-b65a-4d5c3171402c.png)

请更新后再次重试，已尝试修复
